# Use the official Nginx image as the base
FROM nginx:1-alpine

# Copy the custom Nginx configuration file into the image
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the public folder into the image
COPY public /usr/share/nginx/html/public

# Expose the default Nginx port
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
